# Generated by Django 3.2.16 on 2023-04-19 19:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('collaboration', '0001_initial'), ('collaboration', '0002_collaborationrequest_viewed'), ('collaboration', '0003_collaborationrequest_status'), ('collaboration', '0004_auto_20230417_0535'), ('collaboration', '0005_auto_20230417_1511'), ('collaboration', '0006_remove_collaborationrequest_viewed'), ('collaboration', '0007_auto_20230418_1855'), ('collaboration', '0008_auto_20230419_1839'), ('collaboration', '0009_alter_collaborationrequest_options')]

    initial = True

    dependencies = [
        ('projects', '0007_alter_project_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', ckeditor.fields.RichTextField(blank=True, verbose_name='contacts')),
                ('about', ckeditor.fields.RichTextField(blank=True, verbose_name='about_user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('in_queue', 'in_queue'), ('rejected', 'rejected'), ('adopted', 'adopted')], default='in_queue', max_length=20, verbose_name='status')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('answer', models.TextField(blank=True, help_text='answer_of_project_author', verbose_name='answer__noun')),
            ],
            options={
                'verbose_name': 'collaboration',
                'verbose_name_plural': 'collaborations',
            },
        ),
    ]
