# Generated by Django 3.2.16 on 2023-04-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
