# Generated by Django 3.2.16 on 2023-04-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_collaborationrequest_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='status',
            field=models.CharField(choices=[('in_queue', 'in_queue'), ('rejected', 'rejected'), ('adopted', 'adopted')], default='in_queue', max_length=20, verbose_name='статус проетка'),
        ),
    ]
