# Generated by Django 3.2.16 on 2023-04-17 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0003_collaborationrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='created_at',
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 17, 5, 35, 11, 669833), verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='about',
            field=models.TextField(blank=True, verbose_name='информация о пользователе'),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='contact',
            field=models.TextField(max_length=150, verbose_name='информация о контактах'),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='status',
            field=models.CharField(choices=[('in_queue', 'in_queue'), ('rejected', 'rejected'), ('adopted', 'adopted')], default='in_queue', max_length=20, verbose_name='статус заявки'),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='просмотрено'),
        ),
    ]
