# Generated by Django 3.2.16 on 2023-04-18 18:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0006_remove_collaborationrequest_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationrequest',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='информация о пользователе'),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='contact',
            field=ckeditor.fields.RichTextField(blank=True, max_length=150, verbose_name='информация о контактах'),
        ),
    ]
