# Generated by Django 3.2.16 on 2023-04-19 18:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0007_auto_20230418_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborationrequest',
            options={'verbose_name': 'collaboration', 'verbose_name_plural': 'collaborations'},
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='about_user'),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='answer',
            field=models.TextField(blank=True, help_text='answer_of_project_author', verbose_name='answer__noun'),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='contact',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation_date'),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='status',
            field=models.CharField(choices=[('in_queue', 'in_queue'), ('rejected', 'rejected'), ('adopted', 'adopted')], default='in_queue', max_length=20, verbose_name='status'),
        ),
    ]
