# Generated by Django 3.2.16 on 2023-04-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0008_auto_20230419_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborationrequest',
            options={'verbose_name': 'участие', 'verbose_name_plural': 'участия'},
        ),
    ]
