# Generated by Django 3.2.16 on 2023-04-19 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('comments', '0001_initial'), ('comments', '0002_alter_comment_options'), ('comments', '0003_auto_20230410_1236'), ('comments', '0004_auto_20230410_1305'), ('comments', '0003_alter_comment_project'), ('comments', '0005_merge_20230410_2121'), ('comments', '0006_alter_comment_project'), ('comments', '0007_alter_comment_options'), ('comments', '0008_auto_20230419_1839')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_alter_project_author'),
        ('projects', '0002_alter_imagesgallery_options'),
        ('projects', '0006_auto_20230410_2121'),
        ('projects', '0013_auto_20230419_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['-creation_date'],
            },
        ),
    ]
