# Generated by Django 3.2.16 on 2023-04-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_project'),
        ('comments', '0004_auto_20230410_1305'),
    ]

    operations = [
    ]
