# Generated by Django 3.2.16 on 2023-04-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20230410_2121'),
        ('comments', '0005_merge_20230410_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(help_text='Какому проекту принадлежит комментарий', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project', verbose_name='проект'),
        ),
    ]
