# Generated by Django 3.2.16 on 2023-04-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-creation_date'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
    ]
