# Generated by Django 3.2.16 on 2023-04-19 19:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('rating', '0001_initial'), ('rating', '0002_auto_20230409_0838'), ('rating', '0003_auto_20230409_1900'), ('rating', '0004_alter_projectrating_score'), ('rating', '0005_auto_20230419_1839')]

    initial = True

    dependencies = [
        ('projects', '0013_auto_20230419_1839'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_alter_comment_project'),
        ('projects', '0002_alter_imagesgallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='score')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_project', to='projects.project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_project_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'rating',
                'verbose_name_plural': 'ratings',
            },
        ),
    ]
