# Generated by Django 3.2.16 on 2023-04-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrating',
            options={'verbose_name': 'рейтинг проетка', 'verbose_name_plural': 'рейтинг проектов'},
        ),
        migrations.RenameField(
            model_name='projectrating',
            old_name='rating',
            new_name='score',
        ),
    ]
