# Generated by Django 3.2.16 on 2023-04-09 19:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_alter_comment_project'),
        ('projects', '0002_alter_imagesgallery_options'),
        ('rating', '0002_auto_20230409_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrating',
            name='project',
            field=models.ForeignKey(help_text='Какому проекту принадлежит оценка', on_delete=django.db.models.deletion.CASCADE, related_name='score_project', to='projects.project', verbose_name='проект'),
        ),
        migrations.CreateModel(
            name='CommentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='оценка проекта')),
                ('comment', models.ForeignKey(help_text='Какому комментарию принадлежит оценка', on_delete=django.db.models.deletion.CASCADE, related_name='score_comment', to='comments.comment', verbose_name='комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_comment_user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'рейтинг комментария',
                'verbose_name_plural': 'рейтинг комментариев',
            },
        ),
    ]
