# Generated by Django 3.2.16 on 2023-04-13 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20230409_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrating',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='оценка проекта'),
        ),
    ]
