# Generated by Django 3.2.16 on 2023-04-19 19:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_add_username_unique'), ('users', '0003_alter_user_bio'), ('users', '0002_alter_user_username'), ('users', '0004_merge_0002_alter_user_username_0003_alter_user_bio'), ('users', '0005_auto_20230410_2121'), ('users', '0006_alter_user_email'), ('users', '0007_auto_20230419_1839')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='only_letters_defis_and_underline', max_length=100, unique=True, verbose_name='username')),
                ('bio', models.TextField(default='', max_length=1000, verbose_name='user_bio')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='last_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='user_email')),
                ('normalized_email', users.models.NormalizedEmailField(max_length=254, unique=True, verbose_name='normalized_email')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date_joined')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.User.get_image_filename, verbose_name='avatar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
