# Generated by Django 3.2.16 on 2023-04-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Имя пользователя', max_length=100, unique=True, verbose_name='username'),
        ),
    ]
