# Generated by Django 3.2.16 on 2023-04-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_username_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', help_text='О себе', max_length=1000, verbose_name='bio'),
        ),
    ]
