# Generated by Django 3.2.16 on 2023-04-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
        ('users', '0003_alter_user_bio'),
    ]

    operations = [
    ]
