# Generated by Django 3.2.16 on 2023-04-10 18:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0002_alter_user_username_0003_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', help_text='О себе', max_length=1000, verbose_name='о себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя', max_length=100, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Аватарка', null=True, upload_to=users.models.User.get_image_filename, verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия', max_length=100, null=True, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='normalized_email',
            field=users.models.NormalizedEmailField(help_text='Нормализованная электронная почта', max_length=254, unique=True, verbose_name='нормализованная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Допускаются только буквы, цифры, дефис и нижнее подчеркивание', max_length=100, unique=True, verbose_name='имя пользователя'),
        ),
    ]
