# Generated by Django 3.2.16 on 2023-04-19 19:17

import ckeditor.fields
import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('projects', '0001_initial'), ('projects', '0002_alter_imagesgallery_options'), ('projects', '0003_project_short_description'), ('projects', '0004_project_tags'), ('projects', '0005_alter_project_author'), ('projects', '0006_auto_20230410_2121'), ('projects', '0007_alter_project_author'), ('projects', '0008_auto_20230416_1257'), ('projects', '0009_auto_20230417_0529'), ('projects', '0010_auto_20230417_0535'), ('projects', '0008_auto_20230413_2054'), ('projects', '0009_alter_project_tags'), ('projects', '0010_alter_project_tags'), ('projects', '0008_auto_20230413_2114'), ('projects', '0009_merge_0008_auto_20230413_2054_0008_auto_20230413_2114'), ('projects', '0011_merge_20230418_1854'), ('projects', '0012_auto_20230418_1855'), ('projects', '0011_merge_20230417_2128'), ('projects', '0013_merge_20230418_2350'), ('projects', '0013_auto_20230419_1839'), ('projects', '0014_merge_20230419_2205')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0003_auto_20230410_2121'),
        ('tags', '0005_auto_20230419_1839'),
        ('tags', '0002_alter_tag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='full_description')),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('in_archive', models.BooleanField(default=False, verbose_name='in_archive')),
                ('status', models.CharField(choices=[('idea', 'idea'), ('development', 'in_develop'), ('ended', 'ended')], default='idea', max_length=20, verbose_name='status')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('collaborators', models.ManyToManyField(related_name='colleagues', to=settings.AUTH_USER_MODEL, verbose_name='collaborators')),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='short_description')),
                ('tags', models.ManyToManyField(help_text='5_tags_maximum__lowercase', related_name='projects', to='tags.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ImagesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.directory_path, verbose_name='preview')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_gallery', to='projects.project')),
            ],
            options={
                'verbose_name': 'галерея',
                'verbose_name_plural': 'галереи',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.directory_path, verbose_name='preview')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='projects.project')),
            ],
            options={
                'verbose_name': 'превью',
                'verbose_name_plural': 'превьюшки',
            },
        ),
    ]
