# Generated by Django 3.2.16 on 2023-04-04 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назовите продукт', max_length=150, verbose_name='название')),
                ('description', models.TextField(help_text='Введите описание продукта', verbose_name='описание')),
                ('published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('in_archive', models.BooleanField(default=False, verbose_name='в архиве')),
                ('status', models.CharField(choices=[('development', 'в разработке'), ('ready', 'готов')], default='development', max_length=14, verbose_name='статус проетка')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('author', models.ForeignKey(help_text='Кто автор', on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('collaborators', models.ManyToManyField(related_name='colleagues', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
