# Generated by Django 3.2.16 on 2023-04-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesgallery',
            options={'verbose_name': 'галлерея', 'verbose_name_plural': 'галлереи'},
        ),
    ]
