# Generated by Django 3.2.16 on 2023-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_imagesgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default='', help_text='Введите краткое описание проекта', verbose_name='краткое описание'),
            preserve_default=False,
        ),
    ]
