# Generated by Django 3.2.16 on 2023-04-04 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20230404_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='colleagues', to=settings.AUTH_USER_MODEL, verbose_name='коллабораторы'),
        ),
    ]
