# Generated by Django 3.2.16 on 2023-04-05 16:31

from django.db import migrations
import projects.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=projects.models.directory_path, verbose_name='главная картинка'),
        ),
    ]
