# Generated by Django 3.2.16 on 2023-04-05 16:32

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.directory_path, verbose_name='главная картинка'),
        ),
    ]
