# Generated by Django 3.2.16 on 2023-04-10 18:21

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_alter_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesgallery',
            name='image',
            field=models.ImageField(upload_to=core.models.directory_path, verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='image',
            field=models.ImageField(upload_to=core.models.directory_path, verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(help_text='Кто автор', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
