# Generated by Django 3.2.16 on 2023-04-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20230413_2054'),
        ('projects', '0008_auto_20230413_2114'),
    ]

    operations = [
    ]
