# Generated by Django 3.2.16 on 2023-04-16 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20230410_2121'),
        ('projects', '0008_auto_20230413_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', to='tags.Tag', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='теги'),
        ),
    ]
