# Generated by Django 3.2.16 on 2023-04-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20230410_2121'),
        ('projects', '0009_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', to='tags.Tag', verbose_name='теги'),
        ),
    ]
