# Generated by Django 3.2.16 on 2023-04-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_merge_0008_auto_20230413_2054_0008_auto_20230413_2114'),
        ('projects', '0010_alter_project_tags'),
        ('projects', '0010_auto_20230417_0535'),
    ]

    operations = [
    ]
