# Generated by Django 3.2.16 on 2023-04-22 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_auto_20230419_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='colleagues', to=settings.AUTH_USER_MODEL, verbose_name='collaborators'),
        ),
    ]
