# Generated by Django 3.2.16 on 2023-04-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('received', 'получено'), ('processing', 'в обработке'), ('answered', 'ответ дан')], default='received', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(help_text='тема', max_length=200, verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(help_text='содержание письма', verbose_name='текст'),
        ),
    ]
