# Generated by Django 3.2.16 on 2023-04-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20230419_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='personal_data',
        ),
        migrations.AddField(
            model_name='personaldata',
            name='feedback',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to='feedback.feedback'),
            preserve_default=False,
        ),
    ]
