# Generated by Django 3.2.16 on 2023-04-06 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='name')),
                ('description', models.CharField(help_text='Описание. Максимум 300 символов', max_length=300, verbose_name='description')),
                ('slug', models.SlugField(help_text='Максимум 200 символов', unique=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='slug')),
                ('formatted_name', models.CharField(editable=False, max_length=150, verbose_name='formatted name')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'default_related_name': 'tags',
            },
        ),
    ]
