# Generated by Django 3.2.16 on 2023-04-19 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tags', '0001_initial'), ('tags', '0002_alter_tag_description'), ('tags', '0003_auto_20230410_2121'), ('tags', '0004_alter_tag_is_published'), ('tags', '0005_auto_20230419_1839')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('name', models.CharField(help_text='maximum_30_symbols', max_length=30, verbose_name='name')),
                ('description', models.TextField(help_text='maximum_400_symbols', max_length=400, verbose_name='description')),
                ('slug', models.SlugField(help_text='maximum_50_symbols', unique=True, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='slug')),
                ('formatted_name', models.CharField(editable=False, max_length=35, verbose_name='normalized_name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'default_related_name': 'tags',
            },
        ),
    ]
