# Generated by Django 3.2.16 on 2023-04-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(help_text='Описание. Максимум 300 символов', max_length=300, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название'),
        ),
    ]
