# Generated by Django 3.2.16 on 2023-04-19 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tag_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(help_text='maximum_400_symbols', max_length=400, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='formatted_name',
            field=models.CharField(editable=False, max_length=35, verbose_name='normalized_name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='maximum_30_symbols', max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='maximum_50_symbols', unique=True, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='slug'),
        ),
    ]
